---
- name: Export ALL configuration from Source AAP (2.4 or later)
  ansible.controller.export:
    controller_host: "{{ aap_host }}"
    controller_username: "{{ aap_username }}"
    controller_password: "{{ aap_password }}"
    validate_certs: "{{ aap_validate_certs }}"
    all: "{{ aap_export_all }}"
  register: exported_assets
  delegate_to: localhost
  run_once: true

- name: "Ensure export directory exists"
  ansible.builtin.file:
    path: "{{ export_dir }}"
    state: directory
    mode: '0755'
        
- name: "Save each asset type to a separate file"
  ansible.builtin.copy:
    content: "{{ item.value | to_nice_json }}"
    dest: "{{ export_dir }}/{{ item.key }}.json"
  loop: "{{ exported_assets | dict2items | rejectattr('key', 'in', ['changed', 'failed']) | list }}"
  loop_control:
    label: "{{ item.key }}"

- name: Export completed
  ansible.builtin.debug:
    msg: "Successfully exported AAP configuration to {{ aap_export_file_path }}."
