---
# roles/aap_migration/tasks/main.yml

- name: Include Export Tasks
  ansible.builtin.include_tasks: export.yml
  when: aap_migration_action in ['export', 'all']

- name: Include Import Tasks
  ansible.builtin.include_tasks: import.yml
  when: aap_migration_action in ['import', 'all']
