---
# ---------------------------------------------------------
# Action Control ('all', 'export', or 'import')
# ---------------------------------------------------------
aap_migrate_action: 'all'

# ---------------------------------------------------------
# Source AAP Details (Used during Export)
# ---------------------------------------------------------
aap_migrate_source_host: "https://aap24.yourdomain.com"
aap_migrate_source_username: "admin"
aap_migrate_source_password: "YourAAP24Password"

# ---------------------------------------------------------
# Destination AAP Details (Used during Import)
# ---------------------------------------------------------
aap_migrate_dest_host: "https://aap26.yourdomain.com"
aap_migrate_dest_username: "admin"
aap_migrate_dest_password: "YourAAP26Password"

# ---------------------------------------------------------
# General Settings
# ---------------------------------------------------------
aap_migrate_validate_certs: false
aap_migrate_export_dir: "./aap_exports"

# ---------------------------------------------------------
# Asset Selection
# ---------------------------------------------------------
aap_migrate_assets:
  projects: 'all'
  job_templates: 'all'
  users: 'all'
  
