---
- name: Export Config from Controller
  hosts: localhost
  gather_facts: false
  environment:
    CONTROLLER_HOST: "{{ controller }}"
    CONTROLLER_TOKEN: '{{ token }}'
      
  tasks:
    - name: Export 
      ansible.controller.export:
        users: 'all'
      register: export

    - name: Print Export
      ansible.builtin.debug:
        var: export
