---
- name: Export Config from Controller
  hosts: localhost
  gather_facts: false
  environment:
    CONTROLLER_HOST: "{{ controller }}"
    CONTROLLER_USERNAME: '{{ user }}'
    CONTROLLER_PASSWORD: '{{ password }}'
      
  tasks:
    - name: Export all assets from Controller
      ansible.controller.export:
        all: True
      register: export

    - name: Print Export
      ansible.builtin.copy:
        dest: /tmp/export.json
        content: '{{ export }}'
