---
- name: Export Config from Controller
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: '{{ controller }}'
    controller_oauthtoken: '{{ token }}'
      
  tasks:
    - name: Export all assets from Controller
      ansible.controller.export:
        inventory: 'all'
        #all: True
      register: export

    - name: Print Export
      ansible.builtin.debug:
        var: export
